Repository OhMyGuus/BetterCrewLink, pull requests merged in 2021-06, with the labels that each got.

#217 Feature/open all platforms - take two
  package.json
  src/common/GamePlatform.ts
  src/common/ISettings.d.ts
  src/common/ipc-messages.ts
  src/main/ipc-handlers.ts
  src/renderer/App.tsx
  src/renderer/Menu.tsx
  src/renderer/language/languages.ts
  src/renderer/settings/Settings.tsx
  static/locales/cs/translation.json
  static/locales/de/translation.json
  static/locales/en/translation.json
  static/locales/eo/translation.json
  static/locales/es-US/translation.json
  static/locales/es/translation.json
  static/locales/fr/translation.json
  static/locales/id/translation.json
  static/locales/pl/translation.json
  static/locales/pt-BR/translation.json
  static/locales/ru/translation.json
  static/locales/sk/translation.json
  static/locales/sl/translation.json
  static/locales/sv/translation.json
  static/locales/tr/translation.json
  static/locales/tt-RU/translation.json
  static/locales/uk/translation.json
Labels: Feature, WIP

#219 Feature/new update
  package.json
  src/common/AmongUsState.ts
  src/common/ObsOverlay.ts
  src/main/GameReader.ts
  src/main/offsetStore.ts
  src/renderer/Menu.tsx
  src/renderer/Overlay.tsx
  src/renderer/Voice.tsx
Labels: WIP

#222 README.md
  README.md
Labels: Under Review, WIP

#224 Disable audio processing for soundbar
  src/renderer/settings/MicrophoneSoundBar.tsx
Labels: WIP

#225 Feature/mod icon
  src/main/GameReader.ts
  src/main/offsetStore.ts
Labels: Needs Testing
